DELETE http://localhost:3003/api/blogs/PUT_ID_HERE
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZ2dlcnMiLCJpZCI6IjVjZDg0NTM3MThmNzUyMzFhOWY5NzU5NCIsImlhdCI6MTU1NzY4MDQ5NX0.KOrmoLjgt1CqXI9CI8_tSOmNCM6gT9vWfQZ5oTObIGg
